language: python
python: 3.4
env:
  - TOXENV=flake8
  - TOXENV=py26-py
  - TOXENV=py26-cy
  - TOXENV=py27-py
  - TOXENV=py27-cy
  - TOXENV=py33-py
  - TOXENV=py33-cy
  - TOXENV=py34-py
  - TOXENV=py34-cy
  - TOXENV=pypy
install:
  - pip install tox cython
  - make build_ext
script:
  - tox -v
