sudo: false
language: python

python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
  - 3.7
  - pypy

matrix:
  include:
    - python: 3.6
      script: tox -e flake8


install:
  - pip install cython tox

script:
  - tox -e py
