language: python
python:
  - 2.7
  - 3.3
  - 3.4
  - pypy
install:
  - pip install cython
  - python setup.py build_ext --inplace
  - pip install -e ".[dev]"
script:
  - flake8 .
  - cd tests; nosetests -v
